### ISSUE TITLE
Desativar campos Bairro e Número no plugin

### ISSUE THREAD

**Issue by dnet5** [claudiosmweb/woocommerce-extra-checkout-fields-for-brazil#15]
Olá, Cláudio.

Pesquisei nos tópicos do wordpress, principalmente no post https://wordpress.org/support/topic/remover-campos-obrigatorios?replies=8, mas não encontrei resposta para esta questão. Como posso desativar estes dois campos?

Dei uma olhada no plugin class-wc-ecfb-front-end.php e vi que há referências ao neighborhood nas linhas 54, 59, 290, 291, 292, 293, 447, 448, 449, 450, 540, 557, 572, 587 e 603 e ao number em 53, 58, 274, 275, 276, 277, 431, 432, 433, 434, 540, 556, 571, 586 e 602.
É no front end que eu desabilito mesmo?

Não sou programador e tenho muito pouco conhecimento em programação, mas pelo que vi nas linhas 57, 58 e 59 esses campos aparecerem porque estão na categoria shipping e não billing, estou certo? Se houver alguma maneira de desabilitar esse shipping diretamente, acredito que seja até mais fácil.

Informo que não estou usando meios de pagamento no site (utilizo o Pay on Contact), então posso desabilitar estes campos tranquilamente, acredito eu.

Poderia me ajudar?

Muito obrigado!

**Comment by claudiosmweb** [comment]
A intenção é não desativar esses campos.
Se não quer eles é melhor não usar o plugin.

**Comment by dnet5** [comment]
Não conseguimos um meio termo aí, Claudio? =/

O plugin é muito bom, mas como **por enquanto** não estou usando esses campos, não queria correr para outra solução. Eu apenas deixaria desativado temporariamente, e depois, quando adicionasse novos meios de pagamento, ativaria novamente os campos.

Abs e obrigado!

**Comment by claudiosmweb** [comment]
Não.

**Comment by dnet5** [comment]
Ok. Obrigado!
