### ISSUE TITLE
Mascaras continuam sendo aplicadas quando o país selecionado não é o Brasil

### ISSUE THREAD

**Issue by smorales** [claudiosmweb/woocommerce-extra-checkout-fields-for-brazil#16]
Quando mudo para outro país as mascaras para o CEP e o telefone continua forçando o padrão do Brasil. Por exemplo, eu mudo o país de Brasil para Alemanha e o CEP continua no formato 99999-999, sendo que na Alemanha o CEP tem outro formato. A mesma coisa vale para o telefone. 
Tem como mudar isso? 

Obrigado.

**Comment by claudiosmweb** [comment]
Por enquanto não.
Se quiser fazer um Pull Request para funcionar apenas quando o pais é o brasil eu agradeço

**Comment by smorales** [comment]
Ok, sem problemas. Fiz umas alterações no comportamento e o plugin está agora aplicando as mascaras para Alemanha, Brasil, Dinamarca, França, Espanha, Suiça, Inglaterra, Estados Unidos e Portugal. Para outros países as mascaras não são aplicadas, mas podem ser adicionadas futuramente. Mandei um Pull Request.
