### ISSUE TITLE
Campo CEP é o último exibido

### ISSUE THREAD

**Issue by phmazzoni** [claudiosmweb/woocommerce-extra-checkout-fields-for-brazil#19]
Prezados,

Não consigo colocar o CEP para vir antes do Endereço, ele está sendo exibido como o último campo.
Alguma dica?

Obrigado

**Comment by claudiosmweb** [comment]
Template quebrado, porque ele muda de lugar lá pra cima.

**Comment by pandoapps** [comment]
Senhores, passamos pelo mesmo problema por aqui e notamos que o campo CEP aparece sempre DEPOIS do campo país.

Com uma linha de CSS deixamos o campo país invisível e alteramos sua posição, conseguindo então posicionar o CEP onde queríamos.
