### ISSUE TITLE
Máscaras Não funcionam no celular

### ISSUE THREAD

**Issue by gs9web** [claudiosmweb/woocommerce-extra-checkout-fields-for-brazil#21]
Olá Cláudio, primeiro gostaria de agradecer ao seu esforço em manter seus plugins, tenho muita confiança no seu trabalho. Mais uma vez Obrigado
Sobre o problema preciso de sua ajuda, não sei se é um problema individual meu, mas as máscaras não funcionam no celular, exemplo vou digitar o cpf 885 a mascara mistura os números, existe uma solução? ou só desativando a máscara? não quero mexer no código porque sei que substituirá em novas atualizações.
no aguardo, e mais uma vez obrigado pela disponibilidade

**Comment by claudiosmweb** [comment]
Recomendo desativar se não esta funcionando.
Pra mim funcionou no Android 5, entretanto o script que estamos usando para fazer isso anda tendo vários problemas com isso https://github.com/digitalBush/jquery.maskedinput/search?q=mobile&type=Issues&utf8=%E2%9C%93
E já tem um tempo que não é atualizado, vou esperar mais um pouco e ver se eles vão atualizar esse script, caso o contrário pensando em trocar por outro.
