### ISSUE TITLE
o meu plugin não fica em portugues só em ingles.

### ISSUE THREAD

**Issue by cleanderson** [claudiosmweb/woocommerce-extra-checkout-fields-for-brazil#22]
Olá instalei o plugin para utilizar o checkout transparente do pagseguro juntamente o wmpl multilingual, porem o wmpl diz que precisa de 4 plugins para funcionar e os mesmo são pagos.
com o extra checkout mesmo com a tradução na linguagens ainda fica em ingles os formularios etc.
Alguem pode me ajudar, pois os formularios, textos, e o ssitema do pagseguro só fica em ingles.

Alguem me ajude por favor.

**Comment by claudiosmweb** [comment]
Esta usando os 4 plugins pagos?
Porque isso dai é problema no WPML, na verdade porque você não esta usando todos os plugins que deveria para fazer isso funcionar e não problema nesse plugin.
