### ISSUE TITLE
WebService não retorna informações de alguns CEPs

### ISSUE THREAD

**Issue by jckronbauer** [claudiosmweb/woocommerce-extra-checkout-fields-for-brazil#25]
Tenho um problema com um cliente, que diz que alguns compradores não conseguem completar o endereço automaticamente digitando o CEP.

Testei o webservice e, realmente, não retorna. Exemplo: http://correiosapi.apphb.com/cep/95833000

Achei outro webservice gratuito, e funcionou: https://viacep.com.br/ws/95833000/json

Eu já tinha feito um fork do teu projeto. Aí eu alterei o meu código e fiz o upload na loja do cliente.

**Comment by claudiosmweb** [comment]
Vou remover essa opção do plugin na próxima versão, não se preocupe.
