### ISSUE TITLE
Compatibility with shipping plugins

### ISSUE THREAD

**Issue by quan-nguyen-quan** [claudiosmweb/woocommerce-extra-checkout-fields-for-brazil#26]
Hi,

Is this compatible with advanced shipping plugins, like [this WooCommerce shipping plugin](http://codecanyon.net/item/wooship-woocommerce-shipping-plugin/13593884) for example?

We are working on an online store for a client in Brazil, installed your plugin to add checkout fields and now there are no shipping rates displayed on Checkout. Can this be related?

**Comment by claudiosmweb** [comment]
No idea, better you test it first.
