### ISSUE TITLE
Loop de Mensagem de erro

### ISSUE THREAD

**Issue by yardz** [claudiosmweb/woocommerce-extra-checkout-fields-for-brazil#28]
Bem, eu encontrei um problema de conflito com o plugin dos correios.

Tema: twentyfifteen
Plugins instalados: WooCommerce Correios, Woocommerce e WooCommerce Extra Checkout Fields for Brazil.

O erro é o seguinte, ao digitar um cep (este no caso 13060-000) o plugin dos correios começa a "recarregar" e exibir um erro. Ele fica criando mensagens de erro sem parar indefinidamente...

Esse erro ocorre quando a "Opção de máscara" está habilitada e a opção "Modo depuração de entrega" (Woocommerce>Status do sistema>Ferramentas) também está habilitada.

Ao desativar qualquer uma das duas opções tudo funciona normalmente.

**Comment by claudiosmweb** [comment]
Não me parece ser um erro neste plugin, já que ele aplica apenas uma mascara.
