### ISSUE TITLE
como editar dados da inscrição estadual depois do pedido ser feito?

### ISSUE THREAD

**Issue by julianojacob** [claudiosmweb/woocommerce-extra-checkout-fields-for-brazil#29]
Não achei como alterar os dados da razão social de um assinante depois que o pedido dele foi concluido.
E teria como este campo ter a mesma função do rg ou cnpj que verifica a sintax dos dados inseridos?

**Comment by claudiosmweb** [comment]
@julianojacob só me dizer a forma de fazer isso que coloco no plugin.

**Comment by julianojacob** [comment]
Quando um usuário cadastrado ou um administrador precisa atualizar ou corrigir dados cadastrais, ele consegue ter acesso  a um botao editar para os campos de Detalhes de Cobrança e Detalhes de Entrega menos para :
Informações do cliente
Razão Social: 
CNPJ: 
Inscrição Estadual: 
Telefone: 
Celular: 
E-mail:

**Comment by claudiosmweb** [comment]
Ahh sim, já da para ele editar, tinha entendido que você queria colocar validação igual temos de CPF e CNPJ.

**Comment by julianojacob** [comment]
editar p mim ainda nao esta disponivel, como faco?

**Comment by claudiosmweb** [comment]
Tenta outro tema.

**Comment by julianojacob** [comment]
infelizmente nao tem como eu sair do tema que estou
vc sabe onde nos arquivos do tema que posso tentar habilitar essa funcao?



*JULIANO JACOB*
design to live

2016-06-11 0:11 GMT-03:00 Claudio Sanches <notifications@github.com>:

**Comment by julianojacob** [comment]
boa noite
troquei de tema e nada de habilitar a edicao dos dados do cliente onde esta
a inscricao estadual
postei uma imagem, todo tema que testei nao habilitou
tem alguma solucao alterando algo no seu plugin?
obrigado pela atencao



*JULIANO JACOB*
design to live

2016-06-13 15:20 GMT-03:00 Juliano Jacob .-superacidshot- <
juliano.jacob@gmail.com>:

**Comment by julianojacob** [comment]
Me passa um orçamento



*JULIANO JACOB*
design to live

Em 21 de junho de 2016 22:46, Juliano Jacob .-superacidshot- <
juliano.jacob@gmail.com> escreveu:

**Comment by claudiosmweb** [comment]
@julianojacob orçamento? se encontrou algum bug corrija e envie Pull Request.
Isso esta funcionando perfeitamente:

![screenshot from 2016-06-24 12-09-08](https://cloud.githubusercontent.com/assets/1264099/16341632/86761888-3a04-11e6-8a12-a52b375516c5.png)
