### ISSUE TITLE
Código do Município Segundo IBGE

### ISSUE THREAD

**Issue by ejrizzi** [claudiosmweb/woocommerce-extra-checkout-fields-for-brazil#33]
Ótimo plug-in, mas para transmitir os dados a um ERP, em alguns casos são necessários alguns códigos, como o código do município no segundo IBGE e o código do País segundo Banco Central. 
Seria interessante permitir que o usuário habilitasse a utilização no WooCommerce destes dois campos, quando o país do cliente for Brasil. Seria possível inclusive montar um Combo Box baseado nestas duas tabelas.
Eu poderia contribuir nesta mudança, mas não sei como fazer.
Saudações.
[paises.txt](https://github.com/claudiosmweb/woocommerce-extra-checkout-fields-for-brazil/files/433191/paises.txt)

[munic.zip](https://github.com/claudiosmweb/woocommerce-extra-checkout-fields-for-brazil/files/433197/munic.zip)

**Comment by claudiosmweb** [comment]
Pode tratar isso direto no seu midway antes de enviar para o ERP, não precisa ser feito neste plugin.

**Comment by ejrizzi** [comment]
Se tratar no Midle e a pessoa digitou uma cidade que não existe não tenho mais como corrigir.

 

Por isso seria interessante tratar no Plug-in, consegue restringir a municípios válidos e que existem na tabela.

 

 

 

De: Claudio Sanches [mailto:notifications@github.com] 
Enviada em: terça-feira, 23 de agosto de 2016 15:52
Para: claudiosmweb/woocommerce-extra-checkout-fields-for-brazil
Cc: ejrizzi; Author
Assunto: Re: [claudiosmweb/woocommerce-extra-checkout-fields-for-brazil] Código do Município Segundo IBGE (#33)

 

Pode tratar isso direto no seu midway antes de enviar para o ERP, não precisa ser feito neste plugin.

**Comment by claudiosmweb** [comment]
Isso é o de menos, da para criar plugin para isso se precisar.
Mas não vejo isso sendo necessário aqui.
