### ISSUE TITLE
Endereço e CEP não exibem

### ISSUE THREAD

**Issue by gabrielzagomarino** [claudiosmweb/woocommerce-extra-checkout-fields-for-brazil#34]
Boa Noite,

Os campos de Endereço (address_1 e address_2) e CEP (postcode) não aparecem na tela de Checkout, apenas os campos Bairro e Número.

Segue o código da minha página de **form-checkout.php**:
[form-checkout.zip](https://github.com/claudiosmweb/woocommerce-extra-checkout-fields-for-brazil/files/469049/form-checkout.zip)

**Comment by claudiosmweb** [comment]
Se não esta exibindo é porque algo esta removendo isso e não é desse plugin, isso eu posso garantir.
Teste os códigos que tem no seu site, plugins e o tema.
