### ISSUE TITLE
Tirar Campos do Checkout

### ISSUE THREAD

**Issue by topfun** [claudiosmweb/woocommerce-extra-checkout-fields-for-brazil#36]
Boa tarde 

Alguns produto é virtual e gratuito, somente necessito que coloque o nome, telefone e email.
Na primeira tela de confirmação tipo de pagamento onde da aceite de dos termos e condições.
Uma vez o valor total sendo igual a zero não precisaria do checkout no meu caso.

Como posso tirar esses campos a mais.

**Comment by claudiosmweb** [comment]
Da mesma forma que você tira qualquer outro campo do WooCommerce.

**Comment by topfun** [comment]
Boa tarde Claudio

Desde ja agradeço pelo retorno

Ja tentei fazer isso via pluguin e não consegui, deve ser feito no arquivo .php?

Qual seria.

Grato pela atenção

Kirk Douglas

**Comment by claudiosmweb** [comment]
Não é para fazer isso neste plugin, até mesmo porque nem precisa fazer.
Basta fazer como faria se tivesse apenas o WooCommerce instalado sem este plugin daqui, vai funcionar do mesmo jeito.

**Comment by topfun** [comment]
Pois é isso mesmo que estive fazendo Sr.
Não existe nenhuma opção de desabilitar obrigatoriedade nos Campos de Checkout do WooCommerce
Caso saiba, seja mais específico

Grato

**Comment by claudiosmweb** [comment]
Tem sim como desabilitar obrigatoriedade dos campos de Checkout do WooCommerce.
Mas isso que você esta perguntando não precisa ser feito neste plugin e não devo ser mais especifico para algo que pode fazer sem este plugin.
