### ISSUE TITLE
Remover obrigatoriedade de CPF se pais não for brasil

### ISSUE THREAD

**Issue by marcussaad** [claudiosmweb/woocommerce-extra-checkout-fields-for-brazil#5]
Claudio,

Você poderia me dar uma luz sobre como fazer o CPF não ser obrigatório se o país não for brasil?

**Comment by claudiosmweb** [comment]
Tem opção para isso dentro do plugin meu jovem.
Vejas as opções do plugin!

**Comment by marcussaad** [comment]
Eu devo estar louco ou cego, porque na versao 3.3.1 não acho essa opção

![img](https://cloud.githubusercontent.com/assets/1544280/5839625/a0e5d492-a176-11e4-8ee7-9193917011f4.jpg)

**Comment by claudiosmweb** [comment]
Parece estar cego sim.

**Comment by marcussaad** [comment]
Não sei em que momento fui mal educado com você, mas ok, se é dessa forma que você acredita ser saudável manter projetos open source, quem sou eu para criticar.

Não sei se não entendeu minha pergunta, não perguntei sobre o campo Tipo de Pessoa, e sim sobre o campo CPF ser obrigatório quando o país não é o Brasil.

**Comment by claudiosmweb** [comment]
Foi mal educado comigo por não ler as descrições das opções do plugin. Alias muito mal educado por não ter pelo menos dado o trabalho de testar as opções.
Esse tipo de coisa prejudica o projeto, enquanto eu poderia estar ajudando alguém com um problema de verdade eu estou aqui respondendo para você sabe algo que você teve preguiça de ler e estar.

Campos de Pessoa Física:

- CPF
- RG

Campos de Pessoa Jurídica:

- CNPJ
- IE

Não tem em nenhum lugar dizendo que vai deixar o campo "Tipo de Pessoa" como não obrigatório.
