### ISSUE TITLE
form checkout

### ISSUE THREAD

**Issue by adolfocscampini** [claudiosmweb/woocommerce-extra-checkout-fields-for-brazil#6]
I need to know if the all form checkout fields, I can use to customer registration?

**Comment by claudiosmweb** [comment]
Yes, you can use the same field for the customer record.
Feel free to do it.

**Comment by adolfocscampini** [comment]
Ok, but how do I put the checkout fields in the customer master record?

**Comment by adolfocscampini** [comment]
Ok, but how do I put the checkout fields in the customer registration?
