### ISSUE TITLE
Problema com a tradução

### ISSUE THREAD

**Issue by mariojhoshi** [claudiosmweb/woocommerce-extra-checkout-fields-for-brazil#7]
Boa tarde Claudio tudo bem?

eu instalei o plugin e chequei a tradução ta toda certa mais não fica em português os campos,
que são adicionados, você sabe me informar se alguém já passou por algum problema parecido.

dá uma olhada por favor: http://clonii.com/site/checkout/

**Comment by claudiosmweb** [comment]
Não é problema relacionado ao plugin.
Você esta fazendo algo errado, deve ter algo instalado junto alterando ou não instalou o WordPress em pt_BR, no lugar pode ter instalado ele em pt_PT.
